# Generated by Django 5.2.4 on 2025-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='이미지'),
        ),
    ]
