# Generated by Django 5.2.4 on 2025-07-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(default='이름없음', max_length=50),
        ),
    ]
