# Generated by Django 5.2.4 on 2025-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0002_remove_post_title_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y%m%d', verbose_name='이미지'),
        ),
    ]
