# Generated by Django 5.2.4 on 2025-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_poster_alter_review_rating_alter_review_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
