# Generated by Django 5.2.4 on 2025-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_actors_review_content_review_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
