# Generated by Django 5.2.4 on 2025-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('멜로/로맨스', '멜로/로맨스'), ('액션', '액션'), ('스릴러', '스릴러'), ('코미디', '코미디'), ('판타지', '판타지'), ('SF', 'SF'), ('범죄', '범죄'), ('전쟁', '전쟁'), ('스포츠', '스포츠'), ('음악/뮤지컬', '음악/뮤지컬'), ('드라마', '드라마')], max_length=20),
        ),
    ]
